import { Link } from "react-router-dom";
import { SiteHeader } from "../components/SiteChrome";
import { Kicker } from "../components/ui";
import { useDocumentTitle } from "../lib/useDocumentTitle";

// Both legal pages share a layout and differ only in content, so they live in
// one file with a `kind` prop rather than two near-identical components.
const UPDATED = "29 July 2026";

function Section({ title, children }) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-2xl font-semibold tracking-tight">
        {title}
      </h2>
      <div className="mt-3 flex flex-col gap-3 leading-relaxed text-cream/70">
        {children}
      </div>
    </section>
  );
}

function Privacy() {
  return (
    <>
      <Section title="What this is">
        <p>
          CampusLens is a student portfolio project, not a commercial service. It
          is offered as-is so people can try it and see how it works.
        </p>
      </Section>

      <Section title="What gets stored">
        <p>
          When you create an account: your email, a display name, and your
          password as a bcrypt hash. The password itself is never stored and
          cannot be recovered from the hash.
        </p>
        <p>
          When you use the app: the courses you create, the text extracted from
          PDFs you upload, your chat history, and any study plans you generate.
        </p>
        <p>
          Uploaded PDF files are deleted from the server once their text has been
          extracted. The extracted text is divided into chunks and stored in
          Pinecone alongside numerical embeddings so your questions can be
          matched against the relevant passages.
        </p>
      </Section>

      <Section title="Who else sees it">
        <p>
          Answering a question sends the relevant excerpts of your notes, plus
          your question, to Google Gemini. Embeddings are stored with Pinecone.
          Account and course data lives in MongoDB Atlas. Hosting is Vercel
          (frontend) and Render (backend).
        </p>
        <p>
          Nothing is sold, and there is no advertising or third-party tracking.
          Anonymous page-view counts are collected through Vercel Analytics,
          which does not use cookies or identify individuals.
        </p>
        <p>
          Unexpected backend errors and their stack traces are sent to Sentry so
          failures can be diagnosed. Before an error is sent, CampusLens removes
          request bodies, cookies, and headers; Sentry is not sent your PDF text,
          questions, authentication cookie, or API credentials.
        </p>
      </Section>

      <Section title="Keeping it or deleting it">
        <p>
          Deleting a course removes its documents, chats, study plans and stored
          embeddings. Chat sessions are automatically removed after seven days of
          inactivity.
        </p>
        <p>
          Your courses are visible only to your account. To have your account and
          everything in it deleted, email the address below.
        </p>
      </Section>

      <Section title="One honest caveat">
        <p>
          This runs on free hosting tiers as a personal project. It should not be
          treated as a secure store for anything sensitive, and please do not
          upload material you are not comfortable sending to a third-party AI
          service.
        </p>
      </Section>
    </>
  );
}

function Terms() {
  return (
    <>
      <Section title="Using CampusLens">
        <p>
          CampusLens is a free student project provided as-is, with no guarantee
          of uptime, accuracy, or that it will continue to exist. It runs on free
          hosting tiers and may be slow, asleep, or unavailable.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You are responsible for what you upload and for keeping your password
          to yourself. Do not upload material you do not have the right to use,
          and do not use the app to break the law or someone else&apos;s rights.
        </p>
        <p>
          The demo account is shared and public. Anything placed in it can be
          seen or removed by anyone, so treat it as a sandbox.
        </p>
      </Section>

      <Section title="About the answers">
        <p>
          Answers are generated by an AI model from your uploaded material. It
          can be wrong, and it can be confidently wrong. Every answer shows the
          passages it came from precisely so you can check it. Do not rely on it
          as your only source when the stakes are your grade.
        </p>
      </Section>

      <Section title="Limits and changes">
        <p>
          Requests are rate-limited and uploads are size-limited to keep the free
          tiers usable for everyone. These terms may change as the project does,
          and the date at the top will change with them.
        </p>
      </Section>
    </>
  );
}

function Legal({ kind }) {
  const isPrivacy = kind === "privacy";
  useDocumentTitle(isPrivacy ? "Privacy" : "Terms");

  return (
    <div className="min-h-dvh bg-night text-cream">
      <SiteHeader />

      <main className="mx-auto w-full max-w-2xl px-6 pb-24 pt-32">
        <Kicker>{isPrivacy ? "Privacy Policy" : "Terms of Use"}</Kicker>
        <h1 className="mt-4 font-display text-5xl font-semibold tracking-tight">
          {isPrivacy ? "What we keep." : "The deal."}
        </h1>
        <p className="mt-4 text-sm text-cream/45">Last updated {UPDATED}</p>

        {isPrivacy ? <Privacy /> : <Terms />}

        <Section title="Contact">
          <p>
            Questions, or want your data removed?{" "}
            <a
              href="mailto:aayush.kskk2@gmail.com"
              className="text-ice underline-offset-4 hover:underline"
            >
              aayush.kskk2@gmail.com
            </a>
          </p>
        </Section>

        <div className="mt-12 flex gap-6 text-sm">
          <Link
            to={isPrivacy ? "/terms" : "/privacy"}
            className="text-ice underline-offset-4 hover:underline"
          >
            {isPrivacy ? "Terms of Use" : "Privacy Policy"}
          </Link>
          <Link to="/" className="text-cream/40 transition-colors hover:text-cream">
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}

export default Legal;
